module.exports = {
  important: true,
  // purge: [
  //     './src/**/*.html',
  //     './src/**/*.vue',
  //     './src/**/*.jsx',
  //     './src/**/*.js',
  //     './src/**/*.ts',
  //   ],
  theme: {
    screens: {
      'sm': {'min': '350px', 'max': '767px'},
      'md': {'min': '768px', 'max': '1023px'},
      'lg': {'min': '1024px', 'max': '1279px'},
      'xl': {'min': '1280px'},
    },
    extend: {
      width: {
        "6%": "6%",
        "1/7": "14%",
        "2/7": "29%",
        "3/7": "43%",
        "4/7": "57%",
        "5/7": "71%",
        "6/7": "86%",
        "7/7": "100%",
        "35%": "35%",
      },
      height: {
        "7": "1.75rem",
        "14": "3.5rem",
        "50%": "50%",
        "92vh": "92vh",
        "70vh": "70vh",
        "33vh": "33vh",
      },
      margin: {
        "10%": "10%",
      },
      inset: {
        "33%": "33%",
        "25%": "25%",
        "5%": "5%",
        "3%": "3%",
        "25vh": "25vh",
        "5vh": "5vh",
        "3vh": "3vh",
        "1vh": "1vh",
      },
      colors: {
        "esatta.red": "#EC165B",
        "button.red": "#F20059",
        progress: "#E14B5A",
        "input.bg": "#F9F9F9",
        "input.border": "#001937",
        "disabled.btn": "#929292",
        "enabled.btn": "#001937",
        "alert.red": "#E51D04",
        "alert.green": "#00CD5C",
        "light.grey": "#454545",
        "popup.red.border": "#FF6282",
        "popup.blue": "#001838",
        "button.grey": "#D8D8D8",
        "grey.bg": "#F5F5F5",
        "feedback.success": "#5E57B8",
      },
      text: {
        "2.5xl": "1.75rem",
      },
      fontFamily: {
        Futura: "Futura",
        Georgia: "Georgia",
        Roboto: "Roboto, sans-serif",
      },
      display: {
        "display": "contents",
      },
    },
  },
  variants: {},
  plugins: [require("@tailwindcss/custom-forms")],
}